version: 1.0.{build}
image: Visual Studio 2013


init:
  - cmd: echo init
install:
  - set PATH=C:\MinGW\bin;%PATH%
  - dir c:\
build_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - make tester examples
