version: 1.0.{build}
image: Visual Studio 2013

build_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - MSBuild C:\projects\libui\build\ALL_BUILD.vcxproj /p:Configuration=Debug
  - dir C:\projects\libui\build
