version: 1.0.{build}
image: Visual Studio 2013
init:
  - cmd: echo init
install:
  - cmd: echo test
build_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - make tester examples
