version: 1.0.{build}
image: Visual Studio 2013

build_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - msbuild C:\projects\libui\build\libui.sln /t:Build /p:Configuration=Release
  - dir C:\projects\libui\build /s

after_build:
  - 7z a -ttar libui-shared-windows-%APPVEYOR_REPO_TAG_NAME%.tar C:\projects\libui\build\out\Release\libui.*
  - 7z a -tgzip libui-shared-windows-%APPVEYOR_REPO_TAG_NAME%.tar.gz libui-shared-windows-%APPVEYOR_REPO_TAG_NAME%.tar

deploy:
  provider: GitHub
  auth_token:
    secure: NsjIRhcaEJhoikwjMS95GRf0eP9TsniXblMLw9s+C/pwOnZrMHCAbw+HGDKRcYhj # your encrypted token from GitHub
  artifact: /.*\.tar.gz/            # upload all NuGet packages to release assets
  force_update: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
