version: 1.0.{build}
image: Visual Studio 2013

build_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - msbuild C:\projects\libui\build\libui.sln /t:Build /p:Configuration=Release
  - dir C:\projects\libui\build /s

after_build:
  - mkdir C:\projects\artifacts
  - 7z a -ttar C:\projects\artifacts\libui-shared-windows-%APPVEYOR_REPO_TAG_NAME%.tar C:\projects\libui\build\out\Release\libui.*
  - 7z a -tgzip C:\projects\artifacts\libui-shared-windows-%APPVEYOR_REPO_TAG_NAME%.tar.gz libui-shared-windows-%APPVEYOR_REPO_TAG_NAME%.tar
  - 7z a -ttar C:\projects\artifacts\examples-shared-windows-%APPVEYOR_REPO_TAG_NAME%.tar C:\projects\libui\build\out\Release\*.*
  - 7z a -tgzip C:\projects\artifacts\examples-shared-windows-%APPVEYOR_REPO_TAG_NAME%.tar.gz examples-shared-windows-%APPVEYOR_REPO_TAG_NAME%.tar
  - dir C:\projects\artifacts

artifacts:
  - path: C:\projects\artifacts\libui-shared-windows-*.tar.gz
    name: shared
  - path: C:\projects\artifacts\examples-shared-windows-*.tar.gz
    name: examples

deploy:
  provider: GitHub
  auth_token:
    secure: NsjIRhcaEJhoikwjMS95GRf0eP9TsniXblMLw9s+C/pwOnZrMHCAbw+HGDKRcYhj # your encrypted token from GitHub
  artifact: /C:\\projects\\artifacts\\.*\.tar\.gz/

  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
