version: 1.0.{build}
image: Visual Studio 2013

build_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - msbuild C:\projects\libui\build\libui.sln /t:Build /p:Configuration=Release
  - dir C:\projects\libui\build /s
  - C:\projects\libui\build\out\Release\test.exe
