version: 1.0.{build}
image: Visual Studio 2013


init:
  - cmd: echo init
install:
  - set PATH=C:\MinGW\bin;%PATH%
  - dir c:\MinGW\bin
  - copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
build_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - dir C:\projects\libui\build
  - MSBuild C:\projects\libui\build\ALL_BUILD.vcxproj /p:Configuration=Release
