version: 1.0.{build}
image: Visual Studio 2013

build_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - msbuild C:\projects\libui\build\libui.sln /t:Build /p:Configuration=Debug;Platform=Win32
  - dir C:\projects\libui\build\out\debug\libui.dll
  - dir C:\projects\libui\build /s
