# 16 october 2015

ifndef inlibuibuild
$(error [FAIL] do not run these makefiles directly)
endif

include $(OS)/GNUosspecific.mk
include common/GNUmakeinc.mk
include $(OS)/GNUmakeinc.mk

HFILES += \
	ui.h \
	ui_$(OS).h

NAME = libui

# GROAN GCC
#CFLAGS += \
#	-fPIC

SUFFIX = $(LIBSUFFIX)

LDFLAGS += \
	-shared
# weird things:
# GROAN GCC
#	-fPIC \
# confused by this
#	-Wl,-soname,$(NAME)$(SUFFIX).0

include GNUbaserules.mk
