# 16 october 2015

include $(OS)/GNUosspecific.mk
include test/GNUmakeinc.mk

HFILES += \
	ui.h

NAME = test

SUFFIX = $(EXESUFFIX)

# TODO what's the difference between doing this and linking to out/libui.so directly?
# LDFLAGS += -L$(OUTDIR) -lui
LDFLAGS += $(OUTDIR)/libui$(LIBSUFFIX)

include GNUbaserules.mk
